name: muslim_todp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  date_picker_timeline: ^1.2.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.1 

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Black.ttf
    - family: cairoNormal
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
